//! Clipboard capture on macOS.
//!
//! `NSPasteboard` has no change notification: the documented way to notice a
//! copy is to watch `changeCount`, which every AppKit clipboard manager does.
//! Reading it is a cheap Mach message, so a half-second poll costs far less
//! than it sounds — and nothing is read from the pasteboard itself until the
//! count has actually moved.

use super::Recorder;
use objc2::rc::autoreleasepool;
use objc2_app_kit::NSPasteboard;
use objc2_foundation::NSString;
use std::time::Duration;

/// How often `changeCount` is read. Fast enough that a copy is archived before
/// the user can reach for the picker, cheap enough to leave running.
const POLL: Duration = Duration::from_millis(500);

/// Pasteboard types worth archiving, mapped to the mime names the rest of the
/// system uses. Keeping one table means the archive holds the same mime for
/// the same content whichever platform recorded it.
const TYPES: &[(&str, &str)] = &[
    ("public.png", "image/png"),
    ("public.jpeg", "image/jpeg"),
    ("public.tiff", "image/tiff"),
    ("public.html", "text/html"),
    ("public.rtf", "text/rtf"),
    ("public.file-url", "text/uri-list"),
    ("public.url", "text/uri-list"),
    ("public.utf8-plain-text", "text/plain;charset=utf-8"),
    // The legacy names, still set by older applications.
    ("NSStringPboardType", "text/plain"),
    ("NeXT TIFF v4.0 pasteboard type", "image/tiff"),
];

/// The types that say "do not remember this".
///
/// `ConcealedType` is confidential content, `TransientType` is about to be
/// replaced and `AutoGeneratedType` was never really copied at all — all three
/// are nspasteboard.org's marks that history should skip. 1Password refuses
/// the standard marks and uses its own, and the last two are older conventions
/// still in the wild. Producers are not consistent about case, so the
/// comparison below ignores it.
///
/// Checked here as well as in the store: recognising it before anything is
/// read means the secret is never copied into this process at all.
const CONCEALED: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.transientpasteboardtype",
    "com.typeit4me.clipping",
];

pub fn watch(recorder: &Recorder) {
    let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
    // Start from whatever is already there rather than archiving the contents
    // of the clipboard as though it had just been copied.
    let mut seen = unsafe { pasteboard.changeCount() };

    loop {
        std::thread::sleep(POLL);

        let current = unsafe { pasteboard.changeCount() };
        if current == seen {
            continue;
        }
        seen = current;

        if let Some(parts) = read(&pasteboard) {
            recorder.record(parts, None);
        }
    }
}

/// Reads every representation worth keeping, or nothing at all when the
/// pasteboard says its contents are a secret.
fn read(pasteboard: &NSPasteboard) -> Option<Vec<(String, Vec<u8>)>> {
    autoreleasepool(|pool| {
        let available = unsafe { pasteboard.types() }?;
        let offered: Vec<String> = available.iter().map(|name| name.to_string()).collect();

        if offered
            .iter()
            .any(|name| CONCEALED.iter().any(|hint| name.eq_ignore_ascii_case(hint)))
        {
            return None;
        }

        let mut parts = Vec::new();
        for (uti, mime) in TYPES {
            if !offered.iter().any(|name| name == uti) {
                continue;
            }
            let key = NSString::from_str(uti);
            let Some(data) = (unsafe { pasteboard.dataForType(&key) }) else {
                continue;
            };
            let bytes = unsafe { data.as_bytes_unchecked() }.to_vec();
            if !bytes.is_empty() {
                parts.push((mime.to_string(), bytes));
            }
        }

        let _ = pool;
        Some(parts)
    })
}
