import Foundation

struct ClipboardEntry: Decodable, Sendable {
    let id: Int64
    let kind: String
    let mimes: [String]
    let bytes: Int64
    let preview: String?
    let pinned: Bool
    let at: Int64
    var caption: String {
        let text = preview?.replacingOccurrences(of: "\n", with: " ") ?? ""
        return text.isEmpty ? ["image": "Изображение", "files": "Файлы", "link": "Ссылка" ][kind] ?? "Запись" : String(text.prefix(120))
    }
}
struct ClipboardStats: Decodable, Sendable {
    let entries: Int64
    let pinned: Int64
    let bytes: Int64
    let budget: Int64
    let retention_days: Int?
}
struct ClipboardPage: Sendable {
    let items: [ClipboardEntry]
    let stats: ClipboardStats
    let more: Bool
}
struct ClipboardFrame: Decodable, Sendable {
    let ev: String
    let v: Int?
    let req: UInt64?
    let items: [ClipboardEntry]?
    let mime: String?
    let bytes: Int64?
    let more: Bool?
    let code: String?
    let message: String?
}
struct ClipboardFailure: Error, LocalizedError, Sendable {
    let message: String
    var errorDescription: String? { message }
}
final class ClipboardTransfer: @unchecked Sendable {
    let mime: String
    let url: URL
    init(mime: String, url: URL) { self.mime = mime; self.url = url }
    deinit { try? FileManager.default.removeItem(at: url) }
}

/// Prefer all portable representations; a restore marks itself autogenerated
/// so the native capture watcher does not create a near-duplicate afterwards.
enum ClipboardTypes {
    static func uti(_ mime: String) -> String? {
        if mime.lowercased().hasPrefix("text/plain") || ["UTF8_STRING", "STRING", "TEXT"].contains(mime) { return "public.utf8-plain-text" }
        return ["text/html": "public.html", "text/rtf": "public.rtf", "application/rtf": "public.rtf", "image/png": "public.png", "image/jpeg": "public.jpeg", "image/tiff": "public.tiff", "image/bmp": "com.microsoft.bmp", "text/uri-list": "public.url", "x-special/gnome-copied-files": "public.url"][mime.lowercased()]
    }
    static func supported(_ entry: ClipboardEntry) -> [String] {
        var seen = Set<String>()
        return entry.mimes.filter { mime in
            guard let type = uti(mime) else { return false }
            return seen.insert(type).inserted
        }
    }
}
